### ISSUE TITLE
Takes a lot of time to animate to the elements in the visible viewport when I scroll down on a ListView.builder

### ISSUE THREAD

**Issue by InvincibleZeal** [mobiten/flutter_staggered_animations#10]
What I suggest is that the delay of the animation of a particular List item should be calculated from the number of items currently mounted above it and not by its index, as I have a Long List and when I scroll down I have to wait for that particular amount of time before it gets animated into the view.

**Comment by MrLepage** [comment]
@InvincibleZeal 
Cannot you just adjust the delay of the animation yourself with the delay parameter of AnimationConfiguration ?

**Comment by InvincibleZeal** [comment]
![staggered-1](https://user-images.githubusercontent.com/42371840/72619516-783c8880-3963-11ea-8d3d-c41d23d156a2.gif)

Here is the code. I know what the `delay` parameter does. All I am asking for is that when I scroll past like 100 items in a ListView, it takes a while for the elements to come into the view after animating as you can see in the screencast above. Can we not just animate only those elements which are currently mounted and are in the visible viewport rather than waiting for `position * delay`  for an item at `position` to trigger its animation. 

```dart
@override
Widget build(BuildContext context) {
  return Scaffold(
    backgroundColor: Colors.purple[50],
    appBar: AppBar(
      title: Text('Testing'),
    ),
    body: ListView.builder(
      itemCount: 200,
      itemBuilder: (context, index) => _listItem(context, index),
    ),
  );
}

_listItem(BuildContext context, int index) {
  return AnimationConfiguration.staggeredList(
    position: index,
    duration: Duration(milliseconds: 300),
    delay: Duration(milliseconds: 100),
    child: SlideAnimation(
      verticalOffset: 100,
      child: FadeInAnimation(
        child: Container(
          color: Colors.white,
          margin: EdgeInsets.symmetric(horizontal: 20, vertical: 5),
          child: ListTile(
            title: Text('List Item $index'),
          ),
        ),
      ),
    ),
  );
}
```

**Comment by MrLepage** [comment]
We can but this is not in our priority for now.

We do not recommend animating list items on scroll.
That's why we have added the `AnimationLimiter` widget to avoid that behaviour.

Feel free to implement the feature and submit a PR :)
