### ISSUE TITLE
Staggered List doesn't work when used with FutureBuilder

### ISSUE THREAD

**Issue by utkarsh-UK** [mobiten/flutter_staggered_animations#11]
**Here is my code:** 
`FutureBuilder<List<String>>(
                        future: MenuService.getMenuCategory(),
                        initialData: [],
                        builder: (ctx, snapshot) {
                          return AnimationLimiter(
                            child: ListView.builder(
                              shrinkWrap: true,
                              scrollDirection: Axis.horizontal,
                              itemCount: snapshot.data.length,
                              physics: BouncingScrollPhysics(),
                              itemBuilder: (chipCtx, index) {
                                final isCatSelected = _selectedCategories
                                    .contains(snapshot.data[index]);

                                return AnimationConfiguration.staggeredList(
                                  position: index,
                                  duration: Duration(seconds: 5),
                                  child: FadeInAnimation(
                                    child: Container(
                                      margin: const EdgeInsets.only(
                                          left: 5.0, right: 5.0),
                                      child: FilterChip(
                                        label: Text(
                                          snapshot.data[index],
                                          style: isCatSelected &&
                                                  !_isAllCatSelected
                                              ? Theme.of(context)
                                                  .textTheme
                                                  .copyWith(
                                                    caption: TextStyle(
                                                        color: Colors.white),
                                                  )
                                                  .caption
                                              : Theme.of(context)
                                                  .textTheme
                                                  .caption,
                                        ),
                                        backgroundColor:
                                            isCatSelected && !_isAllCatSelected
                                                ? Theme.of(context).primaryColor
                                                : Colors.transparent,
                                        shape: StadiumBorder(
                                          side: BorderSide(
                                            color:
                                                Theme.of(context).primaryColor,
                                            width: 1.5,
                                          ),
                                        ),
                                        onSelected: (isSelected) {
                                          if (isSelected) {
                                            if (isCatSelected) {
                                              setState(() {
                                                _isAllCatSelected = false;
                                                _selectedCategories.removeWhere(
                                                    (category) =>
                                                        category ==
                                                        snapshot.data[index]);
                                              });
                                            } else {
                                              setState(() {
                                                _isAllCatSelected = false;
                                                _selectedCategories
                                                    .add(snapshot.data[index]);
                                              });
                                            }
                                          }
                                        },
                                      ),
                                    ),
                                  ),
                                );
                              },
                            ),
                          );
                        },
                      ),`
Here is my code used for staggered animation. This works absolutely fine if I removed FutureBuilder and used any hard coded list.

**Comment by MrLepage** [comment]
Please define what 'doesn't work'

**Comment by utkarsh-UK** [comment]
I want to load list view items with gradually increasing their opacity one after another as shown in repositorie's video example. But it doesn't happen when used with FutureBuilder. All the list items are loaded directly

**Comment by MrLepage** [comment]
@utkarsh-UK 
Try to set a `UniqueKey()` to the `AnimationLimiter` and only update this key when new data are loaded.

**Comment by utkarsh-UK** [comment]
Okay will try that surely, thanks🙌

**Comment by utkarsh-UK** [comment]
Worked like a charm man, thanks for this help🙌
