### ISSUE TITLE
Guidance with using staggered animations with SliverList

### ISSUE THREAD

**Issue by jerh-remy** [mobiten/flutter_staggered_animations#14]
Is it possible to use this library with a SliverList? I'm afraid I haven't seen this use case in the docs.
Here is the code I want to wrap:

```
  return SliverList(
                delegate: SliverChildBuilderDelegate(
                  (context, index) {
                    List<MbTransaction> mbTransaction =
                        snapshot.data.mbTransactions;

                    return TransEnqListTile(
                      transaction: mbTransaction[index],
                      color: double.parse(mbTransaction[index].amount) > 0
                          ? Color(0xff07B226)
                          : Color(0xffE41F0D),
                    );
                  },
                  childCount: snapshot.data.mbTransactions.length,
                ),
              );
```

**Comment by MrLepage** [comment]
Hello @jerh-remy ,

Yes you can :)

It works the same as classic ListView and GridView.

Wrap your `SliverList` in the `AnimationLimiter` widget.
Wrap your items in `Animation` widgets.

Voilà!

**Comment by jerh-remy** [comment]
Thank you so much for the quick reply. Worked like a charm!

**Comment by serbixote** [comment]
Hello!

Do you guys would know how to make it work with a `SliverReorderableList`, I tried just like @MrLepage suggested for SilverList. However, the animation happens when reordering 😭. I didn't see this happening with a regular `ReorderableListView`, and I would love to keep using this package.
