### ISSUE TITLE
Flutter 1.22 Compatibility

### ISSUE THREAD

**Issue by sebastianbuechler** [mobiten/flutter_staggered_animations#23]
I upgraded today to Flutter version 1.22 and it seems that this package is not compatible anymore.

**Comment by MrLepage** [comment]
Hello @sebastianbuechler,
please refer to https://github.com/flutter/flutter/issues/63088#issuecomment-670049450

You will need to update your dart min sdk to 2.8.0.

**Comment by sebastianbuechler** [comment]
> Hello @sebastianbuechler,
> please refer to [flutter/flutter#63088 (comment)](https://github.com/flutter/flutter/issues/63088#issuecomment-670049450)
> 
> You will need to update your dart min sdk to 2.8.0.

Thank you @MrLepage, this did the trick!
