### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by nilsreichardt** [mobiten/flutter_staggered_animations#33]
## Description
All dependencies are migrated to null safety. So we should migrate this package to null safety.

## Resources
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

**Comment by MrLepage** [comment]
Will do when null safety will be officially released and out of beta.

Hopefully tomorrow 🤗

**Comment by nilsreichardt** [comment]
@MrLepage I created a PR: #37. Please check everything.

**Comment by Reinbowsaur** [comment]
Cheers for the update, fixed the issues.

**Comment by MrLepage** [comment]
Released in 1.0.0
