### ISSUE TITLE
Broken in Flutter version 2.0.0

### ISSUE THREAD

**Issue by M123-dev** [mobiten/flutter_staggered_animations#34]
> ../../../../../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_staggered_animations-0.1.2/lib/src/animation_configuration.dart:161:20: Error: The method 'ancestorWidgetOfExactType' isn't defined for the cl
> ass 'BuildContext'.
>  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../../../../../SDK/flutter/packages/flutter/lib/src/widgets/framework.dart').
> Try correcting the name to the name of an existing method, or defining a method named 'ancestorWidgetOfExactType'.
>     return context.ancestorWidgetOfExactType(AnimationConfiguration)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../../../../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_staggered_animations-0.1.2/lib/src/animation_limiter.dart:75:20: Error: The method 'ancestorWidgetOfExactType' isn't defined for the class 'Bu
> ildContext'.
>  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../../../../../SDK/flutter/packages/flutter/lib/src/widgets/framework.dart').
> Try correcting the name to the name of an existing method, or defining a method named 'ancestorWidgetOfExactType'.
>     return context.ancestorWidgetOfExactType(_AnimationLimiterProvider)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
>

**Comment by MrLepage** [comment]
I guess they have removed the
```ancestorWidgetOfExactType```
method.

Library update will be released before the end of the week.

**Comment by pengzhenkun** [comment]
多久修复这个问题，急！

**Comment by pengzhenkun** [comment]
../../../../../Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_staggered_animations-0.1.2/lib/src/animation_configuration.dart:161:20: Error: The method 'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../../../../Library/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorWidgetOfExactType'.
    return context.ancestorWidgetOfExactType(AnimationConfiguration)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../../Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_staggered_animations-0.1.2/lib/src/animation_limiter.dart:75:20: Error: The method 'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../../../../Library/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorWidgetOfExactType'.
    return context.ancestorWidgetOfExactType(_AnimationLimiterProvider)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

**Comment by hsangtini** [comment]
Really need to upgrade flutter, hope update available soon. Thanks.

**Comment by MrLepage** [comment]
Fixed in 0.1.3.

**Comment by MrLepage** [comment]
Released :)

**Comment by M123-dev** [comment]
Thanks, is working great 👍🏻
