### ISSUE TITLE
is it possibile to restart animation?

### ISSUE THREAD

**Issue by scognito** [mobiten/flutter_staggered_animations#4]
I have a screen (screen1) with ListView and 3 elements animated (working as expected).
When I click on an item, I load a new screen using Navigator (screen2).
When I go back from screen2 to screen1, there is obviously no animation again, but I would like to have a way to restart the animation.
Is this possible?

**Comment by MrLepage** [comment]
This is not a use-case directly supported by the library.

You will need two things :
- detect that your previous screen is resumed
- rebuild the list so the animation is played again
