### ISSUE TITLE
Only apply animation on entry

### ISSUE THREAD

**Issue by Depechie** [mobiten/flutter_staggered_animations#46]
Currently when I use the `FadeInAnimation` on a Horizontal ListView, I will always get the fading when scrolling left to right. Even though the items where already added to the listview.

Can we stop the animation and only animate on first render/entry?

**Comment by KristianBalaj** [comment]
As you can see in the documentation, use the AnimationLimiter.

**Comment by Depechie** [comment]
Thx for pointing that out! Seems I missed that somehow.
Will try this, thx!

**Comment by Depechie** [comment]
Works like a charm!
