### ISSUE TITLE
WidgetsBinding warnings after upgrading to Flutter 3.0

### ISSUE THREAD

**Issue by UsamaKarim** [mobiten/flutter_staggered_animations#50]
After upgrading to latest Flutter release 3.0, some warnings started appearing in the console logs. Hopefully these are only warnings.

```
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/src/animation_limiter.dart:43
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance!.addPostFrameCallback((Duration value) {
```

The error is generated from line https://github.com/mobiten/flutter_staggered_animations/blob/780941c20a088d8314c2e5a141bd2215ea294738/lib/src/animation_limiter.dart#L43

**Comment by UsamaKarim** [comment]
Thanks to @mfrischbutter for pushing PR #49

**Comment by barbrady91** [comment]
I have the same problem. Since Flutter 3.0 WidgetsBinding.instance can't be null anymore. The exclamation mark has to be removed to fix this issue.

**Comment by purgeyao** [comment]
@MrLepage Do you have any plans to fix this

**Comment by nbnD** [comment]
Same problem

**Comment by alexaung** [comment]
> ../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_staggered_animations-1.0.0/lib/src/animation_limiter.dart:43:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((Duration value) {

**Comment by kpk-i710** [comment]
yes, same problem

**Comment by o-sergeneser** [comment]
same problem

**Comment by zhaopingfu** [comment]
same problem

**Comment by abdulmominsakib** [comment]
@MrLepage I guess you can merge the pr of @mfrischbutter

**Comment by UsamaKarim** [comment]
#51 has better stance to be merged.

**Comment by Tkko** [comment]
Before the merge you can depend on my [PR](https://github.com/mobiten/flutter_staggered_animations/pull/51) directly

```
  flutter_staggered_animations:
    git:
      url: https://github.com/Tkko/flutter_staggered_animations
      ref: Flutter-3.0.0
```

**Comment by kpk-i710** [comment]
> Перед слиянием вы можете напрямую зависеть от моего [PR](https://github.com/mobiten/flutter_staggered_animations/pull/51)
> 
> ```
>   flutter_staggered_animations:
>     git:
>       url: https://github.com/Tkko/flutter_staggered_animations
>       ref: Flutter-3.0.0
> ```

for some reason does not work, the dependency does not allow to import

**Comment by Tkko** [comment]
> > Перед слиянием вы можете напрямую зависеть от моего [PR](https://github.com/mobiten/flutter_staggered_animations/pull/51)
> > ```
> >   flutter_staggered_animations:
> >     git:
> >       url: https://github.com/Tkko/flutter_staggered_animations
> >       ref: Flutter-3.0.0
> > ```
> 
> for some reason does not work, the dependency does not allow to import

Is `pub get` failing? if yes what's an error?

**Comment by kpk-i710** [comment]
> flutter_staggered_animations:
>     git:
>       url: https://github.com/Tkko/flutter_staggered_animations
>       ref: Flutter-3.0.0
in pub get is imported without problems, only when I want to use in a dart file import 'package:flutter_staggered_animations/flutter_staggered_animations.dart'; he does not work

**Comment by chornthorn** [comment]
Same problem

**Comment by adnankhan74444** [comment]
same problem

**Comment by fredgrott** [comment]
need to check and see if everyone is in fact setting Widget Bindings as part of their app initialization in main as I do that and do not get the errors.

**Comment by UsamaKarim** [comment]
> need to check and see if everyone is in fact setting Widget Bindings as part of their app initialization in main as I do that and do not get the errors.
> 
> In fact I use the Widgets Binding callback to pre load my image assets.

Hey, I initialised `WidgetsFlutterBinding.ensureInitialized()` in main method but still getting these errors.

**Comment by achyusuf10** [comment]
> Before the merge you can depend on my [PR](https://github.com/mobiten/flutter_staggered_animations/pull/51) directly
> 
> ```
>   flutter_staggered_animations:
>     git:
>       url: https://github.com/Tkko/flutter_staggered_animations
>       ref: Flutter-3.0.0
> ```

Thanks, it works

**Comment by williamwiseki** [comment]
Encounter same issue, waiting for upgrade on package

**Comment by faisal-kabir** [comment]
```
flutter_staggered_animations:
    git:
      url: https://github.com/faisal-kabir/flutter_staggered_animations.git
      ref: develop
```
You guys can use this repo, I solved the issue.

**Comment by Miiite** [comment]
Version `1.1.0` was published today to enable the compatibility with flutter 3.0, and remove these warnings. Please open a new issue if you still encounter the same kind of problems with `1.1.0`
