### ISSUE TITLE
How to deal with Expanded ?

### ISSUE THREAD

**Issue by QuentinSc** [mobiten/flutter_staggered_animations#6]
Hello,

Awesome code ;-)
Just a thing, I would like to animate a Column with Expanded widgets. But the ancestor is not anymore a Flex if I use your Widget.

```
> Expanded widgets must be placed directly inside Flex widgets.
> Expanded(no depth, flex: 1, dirty) has a Flex ancestor, but there are other widgets between them:
> - Opacity(opacity: 1.0)
> - Transform
> These widgets cannot come between a Expanded and its Flex.
> 
```

Any tips to work with ?

Thank you very much

**Comment by MrLepage** [comment]
Hello @QuentinSc,
Can you paste a code sample of what you are trying to achieve ?

**Comment by QuentinSc** [comment]
Hello,

I'm trying to animate a widget Column like this one :
Is it possible with your AnimationConfiguration.toStaggeredList widget ?

```
 Column(
        children: <Widget>[
          Expanded(
              flex: 1,
              child: Container(
                color: Colors.blue,
              )),
          Expanded(
              flex: 2,
              child: Row(
                children: <Widget>[
                  Expanded(
                      child: Container(
                    color: Colors.grey,
                  )),
                  Expanded(
                      child: Container(
                    color: Colors.red,
                  )),
                ],
              )),
          Expanded(
              flex: 3,
              child: Container(
                color: Colors.orange,
              )),
        ],
      ),
```

Thank you!

**Comment by simone-bruziches** [comment]
Hi, I have this problem too, I would like to know if there is a way to use Expanded when we use the library on a Row or Column.

Thanks

**Comment by simone-bruziches** [comment]
`import 'package:flutter/material.dart';
import 'package:flutter_staggered_animations/flutter_staggered_animations.dart';

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    double height = MediaQuery.of(context).size.height;
    double width = MediaQuery.of(context).size.width;
    return Scaffold(
      body: SafeArea(
        child: Container(
          height: height * 1,
          width: width * 1,
          child: Row(
            children: AnimationConfiguration.toStaggeredList(
              childAnimationBuilder: (widget) => SlideAnimation(
                horizontalOffset: 50.0,
                child: FadeInAnimation(
                  child: widget,
                ),
              ),
              children: [
                Container(
                  width: width * 0.2,
                  color: Colors.blue,
                ),
                Expanded(
                  child: Column(
                    children: <Widget>[
                      Container(
                        height: height * 0.3,
                        color: Colors.yellow,
                      ),
                      Expanded(
                        child: Container(
                          color: Colors.orange,
                        ),
                      ),
                    ],
                  ),
                ),
                Container(
                  width: width * 0.2,
                  color: Colors.green,
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}
`

This is my code, if I don't use the library, the column inside the line expands and takes all the available space, instead if I use the library, I get the error 

Exception caught by rendering library ═══════ ══════════════════════════
A RenderFlex overflowed by 99784 pixels on the right.
The relevant error-causing widget was
    Row

**Comment by MrLepage** [comment]
The library does not support animations in a column that contains Expanded widgets.

The `toStaggeredList` method simply loop on the row or column children and wrap every child in an `Animation` widget. As `Expanded` widget must be a direct child of Flex widget, it cannot be wrapped.

The only solution for now if you have a fixed list of items to animate is to manually wrap each `Expanded` child in its own `Animation` widget.

**Comment by QuentinSc** [comment]
Thank you, I will wait :)

**Comment by kiaxseventh** [comment]
It has been about 2 years since this issue
are you have plan for ``` Expanded ``` support ?

**Comment by souradeep98** [comment]
I have a work around this problem and came up with a solution. Look at here #55 

I hope it helps.  :)
