### ISSUE TITLE
Sequential variant for StaggeredGrid

### ISSUE THREAD

**Issue by 12people** [mobiten/flutter_staggered_animations#61]
Instead of animating widgets by diagonal lines in a grid, I'd like to be able to animate each item in the grid sequentially in reading order: from left to right (or right to left, for RTL locales), then top to bottom.

Would it be possible to add this variant?

**Comment by MrLepage** [comment]
You can use `AnimationConfiguration.staggeredList`.

It will animate sequentially based on index.

**Comment by 12people** [comment]
@MrLepage staggeredList is used for a 1D list, no? It can't be applied to a 2D grid.

(As for staggeredGrid, it animates from left to right and from top to bottom at the same time. I want a sequential animation in reading order.)

**Comment by MrLepage** [comment]
StaggeredGrid applies a delay to each item based on the item index and a number of columns to produce a "diagonal appearance effect".

StaggeredList applies a delay to each item based only on the item index.

You still can apply StaggeredList to a 2D grid to animate in "reading order".

**Comment by 12people** [comment]
Oh great, I had no idea — thanks!
